### ISSUE TITLE
typeahead v0.11.1

### ISSUE THREAD

**Issue by dongliu** [bassjobsen/typeahead.js-bootstrap-css#11]
The CSS class name changed in v0.11.1, see https://github.com/twitter/typeahead.js/blob/v0.11.1/src/typeahead/www.js for details. 

We will need to add lines like 

```
.tt-menu {
&:extend(.dropdown-menu);
}
```
and keep .tt-dropdown-menu still there to be compatible with old versions. I will submit a pull request.

**Comment by HakanL** [comment]
Can you do a commit for the compiled CSS as well?

**Comment by dongliu** [comment]
I am not sure if you want this https://github.com/hyspace/typeahead.js-bootstrap3.less/blob/master/typeahead.css

**Comment by HakanL** [comment]
I was thinking a commit patch against this repository. But I'm not the maintainer, I was just looking for a CSS fix for typeahead v0.11.1 and found your patch against the less file.

**Comment by dongliu** [comment]
I assume this repository suggests you to compile your own. Here is one I just compiled https://gist.github.com/dongliu/4af9c0622a241c533a84
against Bootstrap v3.3.5

**Comment by HakanL** [comment]
In the readme they were linking to the src/css file: https://github.com/bassjobsen/typeahead.js-bootstrap-css/blob/master/typeaheadjs.css but I'm not sure if it's meant to be a standalone or something else. Maybe the author can comment on that.

**Comment by bassjobsen** [comment]
should work now?
