### ISSUE TITLE
It looks like typeaheadjs.css is missing a lot of stuff

### ISSUE THREAD

**Issue by jfly** [bassjobsen/typeahead.js-bootstrap-css#13]
See https://github.com/bassjobsen/typeahead.js-bootstrap-css/commit/358993f0e3801b57e2b8257321ee7cf04f6dd1aa, where a bunch of important looking stuff was removed.

**Comment by engma** [comment]
+1 Where is the compiled stuff? now I need to make my own version of bootstrap and compile it for this to work

**Comment by scotty6435** [comment]
+1 this latest change completely broke this project.

**Comment by holtkamp** [comment]
:+1:
