### ISSUE TITLE
Problems with input-group-sm / input-group-lg and input-group-addon / input-group-button

### ISSUE THREAD

**Issue by holtkamp** [bassjobsen/typeahead.js-bootstrap-css#22]
As demonstrated in some examples provided by https://github.com/bassjobsen/typeahead.js-bootstrap-css/pull/21, visual problems occur when combining specific input-group functionality. 

Best to be explained with a screenshot.

![screen shot 2016-01-06 at 12 27 49](https://cloud.githubusercontent.com/assets/776405/12141601/2a9d49fa-b471-11e5-8ff9-9cb7a623c3ae.png)

**Comment by bassjobsen** [comment]
@holtkamp thanks for your examples! I should work now, if not please reopen

**Comment by holtkamp** [comment]
@bassjobsen very nice, impressive LESS skills ;). 

When looking at the examples I suggested, I 'could' see some square edges on the right side of the input field when only the ```input-group``` (so no small / large) is used as indicated by the red rectangles below. Certainly not a big thing, but good to mention...

![screen shot 2016-01-07 at 01 11 08](https://cloud.githubusercontent.com/assets/776405/12158677/516e0e00-b4dc-11e5-90c6-bbc96af15fde.png)
