### ISSUE TITLE
Add to Bower

### ISSUE THREAD

**Issue by migig** [bassjobsen/typeahead.js-bootstrap-css#9]
Would make it much easier for us. I'm sure many copy-paste the less into their projects, but I like many prefer to take this as a dependency through Bower. If it works I don't want to fiddle with it, just include it and that's one less thing to worry about.

The [other typeahead plugin stylesheet](https://github.com/hyspace/typeahead.js-bootstrap3.less) already provides Bower support, but their stylesheet is overkill.

Thanks.

**Comment by bassjobsen** [comment]
done

**Comment by migig** [comment]
@bassjobsen Awesome thanks
